# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dbf0a1eba0e04633815b55e744d802beca895bcd9d64ac6b950383a6f6d2d1f99ee4bf5fae0dac42c26d8fc9a8f9d03665b5e3633aae45c056037526553b3f0

test:
  secret_key_base: 03a2a2cf3e8a7aa20574f2f5ed3e4bb11f6d374d1cf1d04a631612b29207fd5cafa3f8e168c82d27b41509387d9570846ada316427359c457c57db6f4047f188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 5dbf0a1eba0e04633815b55e744d802beca895bcd9d64ac6b950383a6f6d2d1f99ee4bf5fae0dac42c26d8fc9a8f9d03665b5e3633aae45c056037526553b3f0
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
